export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const UPDATE_ITEM_QUANTITY = 'UPDATE_ITEM_QUANTITY';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';
export const FETCH_CART = 'FETCH_CART';
export const CHECKOUT = 'CHECKOUT';
export const FETCH_STORE = 'FETCH_STORE';
export const ADD_ITEM_TO_STORE = 'ADD_ITEM_TO_STORE';
export const REMOVE_ITEM_FROM_STORE = 'REMOVE_ITEM_FROM_STORE';
export const EDIT_STORE_ITEM = 'EDIT_STORE_ITEM';
export const FETCH_COCKTAILS = 'FETCH_COCKTAILS';
export const ADD_COCKTAIL_TO_CART = 'ADD_COCKTAIL_TO_CART';

